{% set data = load_setup_py_data() %}
{% set version = "2021.1.2" %}

package:
  name: "phys2320_assessor"
  version: "{{ version }}"

source:
    path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - numpy
    - scipy
    - matplotlib
    - sqlite
    - pylint
    - pygments
    - python
  run:
    - numpy
    - scipy
    - matplotlib
    - sqlite
    - pylint
    - pygments
    - python
    - pygments
    - weasyprint
    - pypdf2
    - uncertainties

about:
  home: "https://github.com/uolphysicsteaching/PHYS2320_Autograder"
  license: "OSI Approved :: BSD 3 clause License"
  license_family: BSD
  license_file: LICENSE
  summary: "A tool for assessing Leeds physics student python coursework."
  doc_url:
  dev_url:
