{% set data = load_setup_py_data() %}

package:
  name: "phys2320_assessor"
  version: {{ data.get('version') }}

source:
  git_tag: main
  git_url: git@github.com:uolphysicsteaching/PHYS2320_Autograder.git
build:
  number: 1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  host:
    - python
    - numpy>=1.18
    - matplotlib>=3.0
    - uncertainties
  run:
    - python
    - numpy>=1.18
    - matplotlib>=3.0
    - uncertainties

about:
  home: {{ data.get('url') }}
  license: BSD 3 Clause License
  license_family: BSD
  license_file: ''
  summary: {{ data.get('description') }}
